version: '3.4'

services:
  kdemo-customer-api:
    image: kdemo-customer-api
    build:
      context: .
      dockerfile: api/Customer.Api/Dockerfile
    restart: on-failure
    env_file: .env
    networks:
      - main-network
    ports:
      - "8081:8081"
    depends_on:
      - kdemo-db
      - kdemo-rabbitmq
  kdemo-catalog-api:
   image: kdemo-catalog-api
   build:
     context: .
     dockerfile: api/Catalog.Api/Dockerfile
   restart: on-failure
   env_file: .env
   networks:
     - main-network
   ports:
     - "8082:8082"
   depends_on:
     - kdemo-db
     - kdemo-rabbitmq
  kdemo-orders-api:
   image: kdemo-orders-api
   build:
     context: .
     dockerfile: api/Orders.Api/Dockerfile
   restart: on-failure
   env_file: .env
   networks:
     - main-network
   ports:
     - "8083:8083"
   depends_on:
     - kdemo-db
     - kdemo-rabbitmq
  kdemo-orders-service:
   image: kdemo-orders-service
   build:
     context: .
     dockerfile: services/Service.Orders/Dockerfile
   restart: on-failure
   env_file: .env
   networks:
     - main-network
   depends_on:
     - kdemo-db
     - kdemo-rabbitmq
  kdemo-db:
   image: kdemo-db
   build:
     context: ./database
     dockerfile: Dockerfile
   env_file: .env
   networks:
      - main-network
   ports:
     - "5432:5432"
  kdemo-rabbitmq:
     image: rabbitmq:3-management
     env_file: .env
     networks:
       - main-network

networks:
   main-network:
     driver: bridge